db:
  datasource: dev:qY1>tK0rI@tcp(localhost:3306)/pf_agent?charset=utf8&parseTime=true
logger:
  dir: /tmp/pf-agent/log
  level: debug
manager:
  server:
    port: 8090
server:
  cors:
    access-control-allow-origin: http://localhost:8081
  mode: debug
  port: 8080
assets:
  root: ./assets
  js: ./assets/js
  css: ./assets/css
  img: ./assets/img
